### ISSUE TITLE
Getting error java.lang.NoSuchMethodError in compile time

### ISSUE THREAD

**Issue by rovkinmax** [VKCOM/vkompose#3]
```
AGP: 8.2.0 / 8.2.1
Kotlin: 1.9.21 / 1.9.22
Compose BOM: 2023.10.01
Compose compiler: 1.5.7 / 1.5.8
Gradle: 8.4
```

Config set up:
```
id("com.vk.vkompose") version "0.3.1"

vkompose {
    skippabilityCheck = true
    // or
    skippabilityCheck {
        // For more see
        // https://android-review.googlesource.com/c/platform/frameworks/support/+/2668595
        // https://issuetracker.google.com/issues/309765121
        stabilityConfigurationPath = "../config/compose/compiler_config.conf"
    }

    recompose {
        isHighlighterEnabled = true
        isLoggerEnabled = true
    }

    testTag {
        isApplierEnabled = true
        isDrawerEnabled = true
        isCleanerEnabled = false
    }

    sourceInformationClean = false
}
```

When I trying build application I facing with error

```
java.lang.NoSuchMethodError: 'java.lang.String org.jetbrains.kotlin.ir.util.DumpIrTreeKt.dump$default(org.jetbrains.kotlin.ir.IrElement, boolean, boolean, int, java.lang.Object)'
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitFunction(SkippableFunctionsCollector.kt:89)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:175)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitSimpleFunction(SkippableFunctionsCollector.kt:34)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:173)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitSimpleFunction(SkippableFunctionsCollector.kt:34)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitSimpleFunction(SkippableFunctionsCollector.kt:34)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:37)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitElement(SkippableFunctionsCollector.kt:43)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitPackageFragment(SkippableFunctionsCollector.kt:34)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitFile(SkippableFunctionsCollector.kt:34)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitFile(SkippableFunctionsCollector.kt:34)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippableFunctionsCollector.visitFile(SkippableFunctionsCollector.kt:34)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:31)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.acceptChildren(IrModuleFragment.kt:48)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at com.vk.compiler.plugin.composable.skippability.checker.ir.SkippabilityChecker.generate(SkippabilityChecker.kt:28)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:225)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:463)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:477)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:400)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:281)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:125)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:657)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:105)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1624)
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by 5hurup** [comment]
Similarly, if you add only id("com.vk.composable-skippability-checker") version "0.3.1"

**Comment by 0xera** [comment]
I have the same problem with other compiler compiler and forgot to fix here. Kotlln 1.9.21-1.9.22 breaks backward compatibility a bit :)

**Comment by 0xera** [comment]
try 0.3.2 version a little later

**Comment by rovkinmax** [comment]
Okay, now I can build, but I return back to issue #1
So, I added configuration in to `app/build.gradle.kts`
```
plugins {
    id("com.vk.vkompose") version "0.3.2"
}

vkompose {
    skippabilityCheck {
        // For more see
        // https://android-review.googlesource.com/c/platform/frameworks/support/+/2668595
        // https://issuetracker.google.com/issues/309765121
        stabilityConfigurationPath = project.rootProject.rootDir.absolutePath + "/config/compose/compiler_config.conf"
    }

    recompose {
        isHighlighterEnabled = true
        isLoggerEnabled = true
    }

    testTag {
        isApplierEnabled = true
        isDrawerEnabled = true
        isCleanerEnabled = false
    }

    sourceInformationClean = true
}
```

Inside Application.onCreate
```
        RecomposeLoggerConfig.isEnabled = true
        RecomposeHighlighterConfig.isEnabled = true
        TestTagDrawConfig.isEnabled = true
```

**Comment by 0xera** [comment]
@rovkinmax you're welcome. I think, it is not right way. So you can create convention gradle plugin in your project to configure modules with compose. If your modules all with compose you can add `allProjects`closure with plugin configuration in root project build.gradle.kts
